services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "passwd"
    volumes:
      - "./schema/mysql.sql:/docker-entrypoint-initdb.d/schema.sql:ro"
    ports:
      - "3300:3306"
