services:
  mysql:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--user=root", "--password=passwd"]
      timeout: 1s
      interval: 1s
      retries: 60
    environment:
      MYSQL_ROOT_PASSWORD: "passwd"
    volumes:
      - "./schema/mysql.sql:/docker-entrypoint-initdb.d/schema.sql:ro"
    ports:
      - "3300:3306"
